services:
  web-app:
    build: .
    image: flow-finance-web_app:0.0.1
    command: python -m core.app
    volumes:
      - /home/jake/projects/Flow-Finance/backend/:/app
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FLOW_DB_URI=${FLOW_DB_URI}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
