name: flow-finance-backend

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      timeout: 5s
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flow-finance-backend:0.0.1
    command: python -m backend.app
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
